version: "3"

tasks:
  gen:
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=.  --go-grpc_opt=paths=source_relative server.proto
      - protoc --plugin=node_modules/ts-proto/protoc-gen-ts_proto --proto_path=. --ts_proto_opt=emitImportedFiles=false,env=node,outputJsonMethods=false,exportCommonSymbols=false,outputServices=grpc-js,outputSchema=false,outputTypeRegistry=false --ts_proto_out=grpc_js:. server/server.proto
    silent: false